name: Release

on:
  push:
    tags:
      - '*'  # triggers on any new tag push

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          VERSION=${{ steps.get_tag.outputs.TAG_NAME }}
          docker build -t juanwz/tasky:"$VERSION" .

      # -------------------------- SECURITY SCAN (Toggle On/Off) --------------------------
      #
      # Uncomment the following step to enable Trivy scanning for CRITICAL vulnerabilities.
      # If a CRITICAL issue is found, the step exits with code 1, failing the workflow.
      #
      # - name: Scan Docker image with Trivy
      #   run: |
      #     VERSION=${{ steps.get_tag.outputs.TAG_NAME }}
      #     # Pull the Trivy image
      #     docker pull aquasec/trivy:latest
      #     # Scan the newly built image
      #     docker run --rm \
      #       -v /var/run/docker.sock:/var/run/docker.sock \
      #       aquasec/trivy:latest image \
      #         --exit-code 1 \
      #         --severity CRITICAL \
      #         --ignore-unfixed \
      #       juanwz/tasky:"$VERSION"      
      

      # -----------------------------------------------------------------------------------

      - name: Push Docker image
        run: |
          VERSION=${{ steps.get_tag.outputs.TAG_NAME }}
          docker push juanwz/tasky:"$VERSION"

      - name: Check out Helm Chart repo
        uses: actions/checkout@v3
        with:
          repository: juanbrny/tasky-chart
          token: ${{ secrets.HELM_CHART_PAT }}
          path: helm-charts  # folder to clone the Helm repo into

      - name: Update Chart.yaml
        id: update_chart
        working-directory: helm-charts
        run: |
          # 1) Parse the existing 'version:' from Chart.yaml
          CURRENT_VERSION=$(grep '^version:' Chart.yaml | sed 's/version: //')

          # 2) Split CURRENT_VERSION into MAJOR, MINOR, PATCH (assuming strict MAJOR.MINOR.PATCH)
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"

          # 3) Increment the PATCH by 1
          patch=$((patch + 1))

          # 4) Compose the new chart version
          NEW_CHART_VERSION="$major.$minor.$patch"

          echo "Current chart version: $CURRENT_VERSION"
          echo "New chart version: $NEW_CHART_VERSION"

          # 5) Replace 'version:' in Chart.yaml with the new chart version
          sed -i "s/^version:.*/version: $NEW_CHART_VERSION/" Chart.yaml

          # 6) Set 'appVersion' to match the container version (the Git tag)
          CONTAINER_VERSION=${{ steps.get_tag.outputs.TAG_NAME }}
          sed -i "s/^appVersion:.*/appVersion: $CONTAINER_VERSION/" Chart.yaml

          # 7) Expose the new chart version as an output for subsequent steps
          echo "NEW_CHART_VERSION=$NEW_CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push chart changes
        working-directory: helm-charts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add Chart.yaml
          git commit -m "Bump chart version + set appVersion to container version"
          git push

      - name: Create a tag in the Helm chart repo
        working-directory: helm-charts
        run: |
          NEW_CHART_VERSION=${{ steps.update_chart.outputs.NEW_CHART_VERSION }}
          git tag "v${NEW_CHART_VERSION}"
          git push origin "v${NEW_CHART_VERSION}"
